[files]

log_file          = /dev/null


compressed_file   = realtime_capture.canz


decompressed_file = realtime_reconstructed.log


schema_file       = schema.txt

[compression]

compression_level = 3

# (main.c: BUFFER_SIZE)
messages_per_block = 50000
