[files]

log_file = ../example_can_log/can_data.log

compressed_file = output.canz

decompressed_file = decompressed.log

schema_file = schema.txt

[compression]

compression_level = 19

messages_per_block = 2000000
